# Generated by Django 3.1.5 on 2021-01-23 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20210123_1740'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='create_on',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='last_modifie',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
